name: CI (yarn)
on: [push]
jobs:
  build:
    name: run `yarn github`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn github
